#####
# This pipeline has a major flaw...it is circular. The put step will trigger the first get step.
#####

resources:
  - name: repo
    type: git
    source:
      uri: git@github.com:roerjo/roerjo.github.io.git
      branch: master
      private_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        ###
        -----END OPENSSH PRIVATE KEY-----

jobs:
  - name: resources-job
    plan:
      - get: repo
        trigger: true
      - task: resources-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gitea/gitea # use any image that has the git cli
 
          inputs:
            - name: repo
          outputs: # Add repo as an output
            - name: repo
          params: # Change these to match your personal info
            EMAIL: roerjo.personal@gmail.com
            GIT_AUTHOR_NAME: Eric Johnson
          run:
            path: sh
            args:
              - -cx
              # this is just a bash script
              - |
                cd repo
                date +%Y-%m-%d > todays-date
                git add ./todays-date
                git config --global user.email $EMAIL
                git config --global user.name $GIT_AUTHOR_NAME
                git commit -m "Update todays date"
      - put: repo
        params:
          repository: repo
